### ISSUE TITLE
Bug: Few Major Database Issues.

### ISSUE THREAD

**Issue by StoneLegion** [moomaxie/BetterShops#4]
So I been using MySQL and doing some testing. I found that I seem to hit quite a few Database issues. The biggest one being that each shop creates a new table. I have never seen another plugin do this as one table should be able to handle Millions of entries without performance loss this seems like a pretty big oversight. Ignoring this though and moving on comes real issues.

When you remove a shop the table does not drop. When you create the shop with the same name the table is not wiped and old entries our still there. It does not seem that these entries are even used as I tried rebooting and the items don't show up in the shop again. But if I add the item again it adds a new table line. I'm a bit confused how this table is working almost seems like the table is a log and not active storage.

Here is a screenshot of me adding the shop adding a lava bucket then removing the shop 100% and creating it over again. You can see keeps just adding new entries. The last Entry on the list the Lava Bucket is what is actually in the shop right now.
http://i.imgur.com/Sks5T8D.png

Also the first time placing an item into a new shop causes the following SQL Error:
http://pastebin.com/xi9aiJDW

Sorry if I'm miss understanding the SQL usage I assumed it was the storage but now checking it out that it seems that it is for logging only but your missing dates and times and such so not really sure what the SQL Feature is.

**Comment by moomaxie** [comment]
The SQL feature was a test that, I'll admit, was a complete failure. More or less it was a test for me (due to the fact that I had rarely used SQL before this). My discoveries and tests in the plugin have forced me to remove it as a feature. 

I'm most likely going to try and fix these issues after release. It was too much for 1.6.0. However, it is not a priority for me to fix/re-add it because I believe that there is no real reason for it. Most likely it won't affect performance (other than possibly making the plugin/server run slower). The plugin is already extremely well optimized and can handle a large amount of shops by file with ease.

**Comment by StoneLegion** [comment]
Sounds good to me. I don't mind using the yml style database anyways. As long done right from the start it should cause next to no performance issues anyways. I used sql for many years and wanted to give it a shot.

I will go ahead and close this then thanks for explaining it :)
